// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"sqlc/pkg/utils"
)

type User struct {
	Username        string `csv:"Username"`
	Identifier      int64  `csv:" Identifier"`
	OneTimePassword string `csv:"One-time password"`
	RecoveryCode    string `csv:"Recovery code"`
	FirstName       string `csv:"First name"`
	LastName        string `csv:"Last name"`
	Department      string `csv:"Department"`
	Location        string `csv:"Location"`
	Created         utils.Time
}
